Logging:
  LogLevel:
    Default: Information
    Microsoft.AspNetCore: Warning

Kestrel:
  EndpointDefaults:
    Protocols: Http2

AppName: AccountService

CookieDomain: ".npon_v2"
CookieAuthenName: NpOn
JwtTokensKey: "h987HG&H&G$T*h*8Yo8Y!&iy8ttg*I$%U_YhKJ$#uG8Q7T_G^87!G@H9QN87*tyh&H$uM!iy$G7_68Rf&$*hY97^8Hu_iYG8!67GFtfG87TG*&^tKioGTK"
IsStartAsync: true
IsUseGrpcStandardMode: true
IsUseEnableUnencryptedMode: true
HostPort: 40004
HostDomain: "http://0.0.0.0"


ConnectionString: "Host=localhost;Port=5432;Username=postgres;Password=password;Database=account;"
ConnectionNumber: 1000 #00

IsUseRedisCache: true
RedisConnectString: "localhost:6379,user=default,password=NpOn.Net-V2_Dragonfly"
RedisConnectionNumber: 1000 #00

#CorsPolicy: NpOnCorsPolicy
CORS: "*"
CorsPolicy: NpOnCorsPolicy

AutoAddCredential: http
DnsResolverFactory: 60
KeepAlivePingDelaySeconds: 60
KeepAlivePingTimeoutSeconds: 30
IsAutomaticKeyGeneration: true
IsDevEnvironment: true

IsUseKafka: false
KafkaConnection: "localhost:19092"
KafkaTopicName: NpOn_V2.AccountService
SaslUsername: npon_admin
SaslPassword: npon_admin_pass

IsUseRabbitMq: true
RabbitMqConnection: "amqp://rabbitmq:password@localhost:5672/"
RabbitMqExchangeName: NpOn_V2.AccountService

LoginTokenExpiresTime: 30
RefreshTokenExpiredTime: 30

IsUseMiddlewareLogger: true
GeneralServiceUrl: "http://localhost:40000"
AccountServiceUrl: "http://localhost:40004"