<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>MicroServices.Tracker.Service.NpOn.TrackerService</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Grpc.AspNetCore" Version="2.64.0"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\..\Common\Applications\ApplicationExtensions\NpOn.AddGrpcAppExtUse\NpOn.AddGrpcAppExtUse.csproj" />
      <ProjectReference Include="..\..\..\..\Common\Applications\ApplicationExtensions\NpOn.RedisAppExtUse\NpOn.RedisAppExtUse.csproj" />
      <ProjectReference Include="..\..\..\..\Common\Applications\NpOn.CommonHttpApplication\NpOn.CommonHttpApplication.csproj" />
      <ProjectReference Include="..\..\..\..\Common\Extensions\NpOn.CommonEnums\NpOn.CommonEnums.csproj" />
      <ProjectReference Include="..\..\..\..\Common\Extensions\NpOn.CommonGrpcCall\NpOn.CommonGrpcCall.csproj" />
      <ProjectReference Include="..\..\..\..\Common\Extensions\NpOn.CommonHeaderConfig\NpOn.CommonHeaderConfig.csproj" />
      <ProjectReference Include="..\..\..\..\Common\Extensions\NpOn.CommonMode\NpOn.CommonMode.csproj" />
      <ProjectReference Include="..\..\..\Account\Service\NpOn.IAccountService\NpOn.IAccountService.csproj" />
      <ProjectReference Include="..\..\..\General\Service\NpOn.IGeneralService\NpOn.IGeneralService.csproj" />
      <ProjectReference Include="..\..\..\..\Common\Applications\ApplicationExtensions\NpOn.ClickHouseAppExtUse\NpOn.ClickHouseAppExtUse.csproj" />
      <ProjectReference Include="..\..\Contract\NpOn.TrackerServiceCommand\NpOn.TrackerServiceCommand.csproj" />
      <ProjectReference Include="..\..\Contract\NpOn.TrackerServiceDomain\NpOn.TrackerServiceDomain.csproj" />
      <ProjectReference Include="..\..\StorageAdapter\NpOn.ITrackerStorageAdapter\NpOn.ITrackerStorageAdapter.csproj" />
      <ProjectReference Include="..\..\StorageAdapter\NpOn.TrackerStorageAdapter\NpOn.TrackerStorageAdapter.csproj" />
      <ProjectReference Include="..\NpOn.ITrackerService\NpOn.ITrackerService.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Update="appsettings.yaml">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="SqlScripts\**\*.sql">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="RedisBroadcast\" />
    </ItemGroup>

</Project>
