CREATE CATALOG pg_facare USING postgresql WITH (
  "connection-url" = 'jdbc:postgresql://124.158.8.9:5432/dbfacare_account',
  "connection-user" = 'postgres',
  "connection-password" = 'fAcar3@pAssW0rd'
);


--docker exec -it scylla1 nodetool status -> datacenter1
DROP CATALOG IF EXISTS scylla;

CREATE CATALOG scylla USING cassandra WITH (
  "cassandra.contact-points" = 'scylla1',
  "cassandra.native-protocol-port" = '9042',
  "cassandra.load-policy.dc-aware.local-dc" = 'datacenter1' -- Thêm .dc-aware vào giữa
);


select * from scylla.scarlight.cfmast as cf, scylla.scarlight.afmast af where cf.custid = af.custid  offset 1 limit 1;

select * from scylla.scarlight.cfmast order by auditdate desc;
