<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>MicroServices.Account.Contracts.NpOn.AccountServiceCommand</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="protobuf-net.Core" Version="3.2.56" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\..\Common\Extensions\NpOn.CommonGrpcContract\NpOn.CommonGrpcContract.csproj" />
      <ProjectReference Include="..\..\Definitions\NpOn.AccountEnum\NpOn.AccountEnum.csproj" />
    </ItemGroup>

</Project>
