<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>MicroServices.Tracker.Contract.NpOn.TrackerServiceReadModel</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\..\Common\Extensions\NpOn.ICommonDb\NpOn.ICommonDb.csproj" />
      <ProjectReference Include="..\..\Definitions\NpOn.TrackerEnum\NpOn.TrackerEnum.csproj" />
    </ItemGroup>

</Project>
