<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>MicroServices.Tracker.StorageAdapter.NpOn.TrackerStorageAdapter</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\..\Common\Infrastructures\DbFactories\NpOn.ClickHouseFactory\NpOn.ClickHouseFactory.csproj" />
      <ProjectReference Include="..\NpOn.ITrackerStorageAdapter\NpOn.ITrackerStorageAdapter.csproj" />
    </ItemGroup>

</Project>
