# docker-compose up -d --scale cf_node=15
# docker-compose restart nginx_balancer

events {
    worker_connections 4096;
}

stream {
    upstream proxy_pool {
        least_conn; 
        server cf_node:1080; 
    }

    server {
        listen 24000;
        proxy_pass proxy_pool;
        proxy_connect_timeout 5s;
    }
}