<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-MigrationService-0a711b21-fdc3-4260-ab83-a50b93f743ea</UserSecretsId>
        <RootNamespace>MicroServices.Migration.Service.NpOn.MigrationService</RootNamespace>
        <AssemblyName>NpOn.MigrationService</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3"/>
    </ItemGroup>

    <ItemGroup>
      <Content Update="appsettings.yaml">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Common\Applications\ApplicationExtensions\NpOn.AddGrpcAppExtUse\NpOn.AddGrpcAppExtUse.csproj" />
      <ProjectReference Include="..\..\Common\Applications\ApplicationExtensions\NpOn.CassandraAppExtUse\NpOn.CassandraAppExtUse.csproj" />
      <ProjectReference Include="..\..\Common\Applications\ApplicationExtensions\NpOn.PostgresAppExtUse\NpOn.PostgresAppExtUse.csproj" />
      <ProjectReference Include="..\..\Common\Applications\ApplicationExtensions\NpOn.RabbitMqAppExtUse\NpOn.RabbitMqAppExtUse.csproj" />
      <ProjectReference Include="..\..\Common\Applications\NpOn.CommonHttpApplication\NpOn.CommonHttpApplication.csproj" />
      <ProjectReference Include="..\..\Common\Extensions\NpOn.CommonGrpcCall\NpOn.CommonGrpcCall.csproj" />
      <ProjectReference Include="..\..\Common\Extensions\NpOn.CommonHeaderConfig\NpOn.CommonHeaderConfig.csproj" />
    </ItemGroup>
</Project>
